// Generated by CoffeeScript 1.3.3
(function() {

  this.HomeController = function($scope, $routeParams, $timeout, GeneFrequencies) {
    return $scope.gene = GeneFrequencies.get({}, function(frequencies) {});
  };

  this.GeneController = function($scope, $routeParams, $timeout, Gene) {
    return $scope.gene = Gene.get({
      gene: $routeParams.gene
    }, function(gene) {
      return $scope.description = gene.data.sections.description.data;
    });
  };

  this.VariantController = function($scope, $routeParams, $timeout, Variant) {
    return $scope.variant = Variant.get({
      variant: $routeParams.variant
    }, function(variant) {
      return $scope.ordered = variant.getOrderedPositions();
    });
  };

  this.StudyController = function($scope, $routeParams, $timeout, Study) {
    return $scope.study = Study.get({
      study: $routeParams.study
    }, function(study) {});
  };

  this.EntityController = function($scope, $routeParams, $timeout, Entity) {
    return $scope.entity = Entity.get({
      study: $routeParams.study,
      role: $routeParams.role,
      identity: $routeParams.identity
    }, function(entity) {});
  };

}).call(this);
