// Generated by CoffeeScript 1.6.2
(function() {
  this.HomeController = function($scope, $routeParams, $timeout, GeneFrequencies) {
    return $scope.gene = GeneFrequencies.get({}, function(frequencies) {});
  };

  this.GeneController = function($scope, $routeParams, $timeout, Gene) {
    return $scope.gene = Gene.get({
      gene: $routeParams.gene
    }, function(gene) {
      return $scope.description = gene.data.sections.description.data;
    }, function(error) {
      return console.log(error);
    });
  };

  this.VariantController = function($scope, $routeParams, $timeout, Variant) {
    return $scope.variant = Variant.get({
      variant: $routeParams.variant
    }, function(variant) {
      return $scope.ordered = variant.getOrderedPositions();
    }, function(error) {
      return console.log(error);
    });
  };

  this.StudyController = function($scope, $routeParams, $timeout, Study) {
    return $scope.study = Study.get({
      study: $routeParams.study
    }, function(study) {}, function(error) {
      return console.log(error);
    });
  };

  this.EntityController = function($scope, $routeParams, $timeout, Entity) {
    return $scope.entity = Entity.get({
      study: $routeParams.study,
      role: $routeParams.role,
      identity: $routeParams.identity
    }, function(entity) {}, function(error) {
      return console.log(error);
    });
  };

  this.EntityStepController = function($scope, $routeParams, $timeout, EntityStep) {
    return $scope.entity = EntityStep.get({
      study: $routeParams.study,
      role: $routeParams.role,
      identity: $routeParams.identity,
      step: $routeParams.step
    }, function(entityStep) {}, function(error) {
      return console.log(error);
    });
  };

}).call(this);
