// Generated by CoffeeScript 1.6.2
(function() {
  angular.module('heliotrope.filters', []).filter('interpolate', [
    'version', function(version) {
      return function(text) {
        return String(text).replace(/\%VERSION\%/mg, version);
      };
    }
  ]).filter('reference', function() {
    return function(input) {
      console.debug(input.id, input.type);
      return "<a href=\"http://www.ncbi.nlm.nih.gov/pubmed/" + input.id + "\" rel=\"external\">" + input.type + ":" + input.id + "</a>";
    };
  });

}).call(this);
